version: "3.8"

services:
  db:
    image: postgres:15
    container_name: student-db
    restart: always
    environment:
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: studentpassword
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: student-api
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://studentuser:studentpassword@db:5432/studentdb
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:

