"""Remove grade column from student

Revision ID: 9602019173c5
Revises: ea5dde7f343b
Create Date: 2025-03-13 07:29:13.960326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9602019173c5'
down_revision = 'ea5dde7f343b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
